name: Mirror any branch to Bitbucket

on:
  push:
    branches:
      - '*'

jobs:
  mirror:
    runs-on: ubuntu-latest

    env:
      BITBUCKET_USER: ximonts
      BITBUCKET_APP_PASSWORD: ${{ secrets.BITBUCKET_APP_PASSWORD }}
      BITBUCKET_REPO: nitsnetsstudios-ondemand/musgrave-pedidosapp-middle

    steps:
      - name: Checkout GitHub repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Push current branch to Bitbucket
        run: |
          git config --global user.name "github-bot"
          git config --global user.email "soporte@nitsnets.com"
          git remote add bitbucket https://$BITBUCKET_USER:$BITBUCKET_APP_PASSWORD@bitbucket.org/$BITBUCKET_REPO.git
          echo "Pushing branch $GITHUB_REF_NAME to Bitbucket..."
          git push bitbucket $GITHUB_REF_NAME
